name: manual_mypy2
permissions: read-all

on:
  workflow_dispatch:
    #paths:
    #  - '.github/workflows/mypy.yml'
    #  - 'pyproject.toml'
    #  - '**.py'
    #  - '**.pyi'

jobs:
  mypy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: 3.9
      - name: Install requirements
        run: |
          choco install -y visualstudio2019buildtools
          choco install -y visualstudio2019-workload-vctools
          #sudo apt-get update
          #sudo apt-get install -y freeglut3 freeglut3-dev libgl1-mesa-dev libglu1-mesa-dev libgstreamer-plugins-base1.0-dev libgtk-3-dev libjpeg-dev libnotify-dev libsdl2-dev libsm-dev libtiff-dev libwebkit2gtk-4.0-dev libxtst-dev python3-dev libhdf5-dev build-essential python3-venv
          #sudo apt-get install python3-wxgtk4.0 python3-numpy python3-scipy python3-pil python3-matplotlib python3-skimage python3-nibabel python3-serial python3-psutil python3-vtk7 python3-vtkgdcm python3-gdcm cython3 python3-h5py python3-imageio python3-keras python3-pubsub
          #pip3 install plaidml-keras
          pip install -r requirements1.txt
      - name: Install invesalius
        run: |
          #pip install -e .
          python3 setup.py build_ext --inplace
      - name: Install mypy
        run: pip install mypy==1.9.0
      - name: Run mypy
        run: |
          #mypy --install-types --non-interactive --config-file pyproject.toml
          #mypy
          mypy .
