name: manual_mypy
permissions: read-all

on:
  workflow_dispatch:
    paths:
      - '.github/workflows/mypy.yml'
      - 'pyproject.toml'
      - '**.py'
      - '**.pyi'

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: 3.9
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Install invesalius
        run: |
          pip install -e .
      - name: Install mypy
        run: pip install mypy==1.9.0
      - name: Run mypy
        run: mypy --install-types --non-interactive
